// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: anvil/v1/sidecar.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorClass is the six-value error taxonomy. The zero value is a sentinel.
// Adding or removing a class is a breaking contract change (hinge-tested).
type ErrorClass int32

const (
	ErrorClass_ERROR_CLASS_UNSPECIFIED      ErrorClass = 0
	ErrorClass_ERROR_CLASS_TRANSPORT        ErrorClass = 1
	ErrorClass_ERROR_CLASS_PROVIDER_REFUSAL ErrorClass = 2
	ErrorClass_ERROR_CLASS_SCHEMA_VIOLATION ErrorClass = 3
	ErrorClass_ERROR_CLASS_ADAPTER_BUG      ErrorClass = 4
	ErrorClass_ERROR_CLASS_TIMEOUT          ErrorClass = 5
	ErrorClass_ERROR_CLASS_CANCELLED        ErrorClass = 6
)

// Enum value maps for ErrorClass.
var (
	ErrorClass_name = map[int32]string{
		0: "ERROR_CLASS_UNSPECIFIED",
		1: "ERROR_CLASS_TRANSPORT",
		2: "ERROR_CLASS_PROVIDER_REFUSAL",
		3: "ERROR_CLASS_SCHEMA_VIOLATION",
		4: "ERROR_CLASS_ADAPTER_BUG",
		5: "ERROR_CLASS_TIMEOUT",
		6: "ERROR_CLASS_CANCELLED",
	}
	ErrorClass_value = map[string]int32{
		"ERROR_CLASS_UNSPECIFIED":      0,
		"ERROR_CLASS_TRANSPORT":        1,
		"ERROR_CLASS_PROVIDER_REFUSAL": 2,
		"ERROR_CLASS_SCHEMA_VIOLATION": 3,
		"ERROR_CLASS_ADAPTER_BUG":      4,
		"ERROR_CLASS_TIMEOUT":          5,
		"ERROR_CLASS_CANCELLED":        6,
	}
)

func (x ErrorClass) Enum() *ErrorClass {
	p := new(ErrorClass)
	*p = x
	return p
}

func (x ErrorClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorClass) Descriptor() protoreflect.EnumDescriptor {
	return file_anvil_v1_sidecar_proto_enumTypes[0].Descriptor()
}

func (ErrorClass) Type() protoreflect.EnumType {
	return &file_anvil_v1_sidecar_proto_enumTypes[0]
}

func (x ErrorClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorClass.Descriptor instead.
func (ErrorClass) EnumDescriptor() ([]byte, []int) {
	return file_anvil_v1_sidecar_proto_rawDescGZIP(), []int{0}
}

type HandshakeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Canonical protocol version the Vault prefers (e.g. "v1").
	CoreProtocolVersion string `protobuf:"bytes,1,opt,name=core_protocol_version,json=coreProtocolVersion,proto3" json:"core_protocol_version,omitempty"`
	// All protocol versions the Vault supports, in preference order.
	SupportedVersions []string `protobuf:"bytes,2,rep,name=supported_versions,json=supportedVersions,proto3" json:"supported_versions,omitempty"`
	// SHA-256 of the Vault's active provider-config content.
	// Compared against sidecar_config_epoch to detect drift.
	VaultConfigEpoch string `protobuf:"bytes,3,opt,name=vault_config_epoch,json=vaultConfigEpoch,proto3" json:"vault_config_epoch,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_anvil_v1_sidecar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_v1_sidecar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_anvil_v1_sidecar_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeRequest) GetCoreProtocolVersion() string {
	if x != nil {
		return x.CoreProtocolVersion
	}
	return ""
}

func (x *HandshakeRequest) GetSupportedVersions() []string {
	if x != nil {
		return x.SupportedVersions
	}
	return nil
}

func (x *HandshakeRequest) GetVaultConfigEpoch() string {
	if x != nil {
		return x.VaultConfigEpoch
	}
	return ""
}

type HandshakeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Negotiated version — the first version in the Vault's `supported_versions` list
	// that the sidecar also supports (preference-order, not lexicographic ordering).
	NegotiatedVersion string `protobuf:"bytes,1,opt,name=negotiated_version,json=negotiatedVersion,proto3" json:"negotiated_version,omitempty"`
	// Sidecar binary version string.
	SidecarVersion string `protobuf:"bytes,2,opt,name=sidecar_version,json=sidecarVersion,proto3" json:"sidecar_version,omitempty"`
	// Sidecar build metadata (commit, timestamp, etc.).
	SidecarBuildInfo string `protobuf:"bytes,3,opt,name=sidecar_build_info,json=sidecarBuildInfo,proto3" json:"sidecar_build_info,omitempty"`
	// SHA-256 of the sidecar's currently loaded provider-config content.
	// On mismatch with vault_config_epoch, the Vault calls ReloadConfig or restarts.
	SidecarConfigEpoch string `protobuf:"bytes,4,opt,name=sidecar_config_epoch,json=sidecarConfigEpoch,proto3" json:"sidecar_config_epoch,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_anvil_v1_sidecar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_v1_sidecar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_anvil_v1_sidecar_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeResponse) GetNegotiatedVersion() string {
	if x != nil {
		return x.NegotiatedVersion
	}
	return ""
}

func (x *HandshakeResponse) GetSidecarVersion() string {
	if x != nil {
		return x.SidecarVersion
	}
	return ""
}

func (x *HandshakeResponse) GetSidecarBuildInfo() string {
	if x != nil {
		return x.SidecarBuildInfo
	}
	return ""
}

func (x *HandshakeResponse) GetSidecarConfigEpoch() string {
	if x != nil {
		return x.SidecarConfigEpoch
	}
	return ""
}

type InvokeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUIDv7 correlation ID; echoed back in all response envelopes.
	IdempotencyKey string `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Model identity string (e.g. "claude-opus-4-7"); used for family-floor check.
	ModelId string `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// Name of the provider connection from anvil.toml to route this call through.
	ProviderConnectionId string `protobuf:"bytes,3,opt,name=provider_connection_id,json=providerConnectionId,proto3" json:"provider_connection_id,omitempty"`
	// Per-call secret material.
	Credentials *Credentials `protobuf:"bytes,4,opt,name=credentials,proto3" json:"credentials,omitempty"`
	// Request payload.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*InvokeRequest_Chat
	//	*InvokeRequest_Embed
	Payload isInvokeRequest_Payload `protobuf_oneof:"payload"`
	// Optional per-call timeout override.
	Timeout       *Timeout `protobuf:"bytes,7,opt,name=timeout,proto3,oneof" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_anvil_v1_sidecar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_v1_sidecar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_anvil_v1_sidecar_proto_rawDescGZIP(), []int{2}
}

func (x *InvokeRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *InvokeRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *InvokeRequest) GetProviderConnectionId() string {
	if x != nil {
		return x.ProviderConnectionId
	}
	return ""
}

func (x *InvokeRequest) GetCredentials() *Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *InvokeRequest) GetPayload() isInvokeRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InvokeRequest) GetChat() *ChatRequest {
	if x != nil {
		if x, ok := x.Payload.(*InvokeRequest_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *InvokeRequest) GetEmbed() *EmbedRequest {
	if x != nil {
		if x, ok := x.Payload.(*InvokeRequest_Embed); ok {
			return x.Embed
		}
	}
	return nil
}

func (x *InvokeRequest) GetTimeout() *Timeout {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type isInvokeRequest_Payload interface {
	isInvokeRequest_Payload()
}

type InvokeRequest_Chat struct {
	Chat *ChatRequest `protobuf:"bytes,5,opt,name=chat,proto3,oneof"`
}

type InvokeRequest_Embed struct {
	Embed *EmbedRequest `protobuf:"bytes,6,opt,name=embed,proto3,oneof"`
}

func (*InvokeRequest_Chat) isInvokeRequest_Payload() {}

func (*InvokeRequest_Embed) isInvokeRequest_Payload() {}

type InvokeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*InvokeResponse_Chat
	//	*InvokeResponse_Embed
	//	*InvokeResponse_Error
	Result        isInvokeResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_anvil_v1_sidecar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_v1_sidecar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_anvil_v1_sidecar_proto_rawDescGZIP(), []int{3}
}

func (x *InvokeResponse) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *InvokeResponse) GetResult() isInvokeResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *InvokeResponse) GetChat() *ChatResponse {
	if x != nil {
		if x, ok := x.Result.(*InvokeResponse_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *InvokeResponse) GetEmbed() *EmbedResponse {
	if x != nil {
		if x, ok := x.Result.(*InvokeResponse_Embed); ok {
			return x.Embed
		}
	}
	return nil
}

func (x *InvokeResponse) GetError() *AnvilError {
	if x != nil {
		if x, ok := x.Result.(*InvokeResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isInvokeResponse_Result interface {
	isInvokeResponse_Result()
}

type InvokeResponse_Chat struct {
	Chat *ChatResponse `protobuf:"bytes,2,opt,name=chat,proto3,oneof"`
}

type InvokeResponse_Embed struct {
	Embed *EmbedResponse `protobuf:"bytes,3,opt,name=embed,proto3,oneof"`
}

type InvokeResponse_Error struct {
	Error *AnvilError `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*InvokeResponse_Chat) isInvokeResponse_Result() {}

func (*InvokeResponse_Embed) isInvokeResponse_Result() {}

func (*InvokeResponse_Error) isInvokeResponse_Result() {}

// InvokeStreamEvent is the unit of the InvokeStreaming response stream.
// Exactly one FinalResult or exactly one Error terminates the stream.
type InvokeStreamEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*InvokeStreamEvent_Token
	//	*InvokeStreamEvent_FinalResult
	//	*InvokeStreamEvent_Error
	//	*InvokeStreamEvent_Heartbeat
	Event         isInvokeStreamEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeStreamEvent) Reset() {
	*x = InvokeStreamEvent{}
	mi := &file_anvil_v1_sidecar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeStreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeStreamEvent) ProtoMessage() {}

func (x *InvokeStreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_v1_sidecar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeStreamEvent.ProtoReflect.Descriptor instead.
func (*InvokeStreamEvent) Descriptor() ([]byte, []int) {
	return file_anvil_v1_sidecar_proto_rawDescGZIP(), []int{4}
}

func (x *InvokeStreamEvent) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *InvokeStreamEvent) GetEvent() isInvokeStreamEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *InvokeStreamEvent) GetToken() *Token {
	if x != nil {
		if x, ok := x.Event.(*InvokeStreamEvent_Token); ok {
			return x.Token
		}
	}
	return nil
}

func (x *InvokeStreamEvent) GetFinalResult() *FinalResult {
	if x != nil {
		if x, ok := x.Event.(*InvokeStreamEvent_FinalResult); ok {
			return x.FinalResult
		}
	}
	return nil
}

func (x *InvokeStreamEvent) GetError() *StreamError {
	if x != nil {
		if x, ok := x.Event.(*InvokeStreamEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *InvokeStreamEvent) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Event.(*InvokeStreamEvent_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isInvokeStreamEvent_Event interface {
	isInvokeStreamEvent_Event()
}

type InvokeStreamEvent_Token struct {
	// Ephemeral token for live display — NOT authoritative for commit.
	Token *Token `protobuf:"bytes,2,opt,name=token,proto3,oneof"`
}

type InvokeStreamEvent_FinalResult struct {
	// Authoritative result — the only event the Vault's commit path consumes.
	FinalResult *FinalResult `protobuf:"bytes,3,opt,name=final_result,json=finalResult,proto3,oneof"`
}

type InvokeStreamEvent_Error struct {
	// Terminal error — Vault must discard all accumulated stream state.
	Error *StreamError `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

type InvokeStreamEvent_Heartbeat struct {
	// Keepalive heartbeat — no semantic content.
	Heartbeat *Heartbeat `protobuf:"bytes,5,opt,name=heartbeat,proto3,oneof"`
}

func (*InvokeStreamEvent_Token) isInvokeStreamEvent_Event() {}

func (*InvokeStreamEvent_FinalResult) isInvokeStreamEvent_Event() {}

func (*InvokeStreamEvent_Error) isInvokeStreamEvent_Event() {}

func (*InvokeStreamEvent_Heartbeat) isInvokeStreamEvent_Event() {}

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_anvil_v1_sidecar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_v1_sidecar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_anvil_v1_sidecar_proto_rawDescGZIP(), []int{5}
}

func (x *Token) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type FinalResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*FinalResult_Chat
	//	*FinalResult_Embed
	Result        isFinalResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalResult) Reset() {
	*x = FinalResult{}
	mi := &file_anvil_v1_sidecar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalResult) ProtoMessage() {}

func (x *FinalResult) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_v1_sidecar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalResult.ProtoReflect.Descriptor instead.
func (*FinalResult) Descriptor() ([]byte, []int) {
	return file_anvil_v1_sidecar_proto_rawDescGZIP(), []int{6}
}

func (x *FinalResult) GetResult() isFinalResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *FinalResult) GetChat() *ChatResponse {
	if x != nil {
		if x, ok := x.Result.(*FinalResult_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *FinalResult) GetEmbed() *EmbedResponse {
	if x != nil {
		if x, ok := x.Result.(*FinalResult_Embed); ok {
			return x.Embed
		}
	}
	return nil
}

type isFinalResult_Result interface {
	isFinalResult_Result()
}

type FinalResult_Chat struct {
	Chat *ChatResponse `protobuf:"bytes,1,opt,name=chat,proto3,oneof"`
}

type FinalResult_Embed struct {
	Embed *EmbedResponse `protobuf:"bytes,2,opt,name=embed,proto3,oneof"`
}

func (*FinalResult_Chat) isFinalResult_Result() {}

func (*FinalResult_Embed) isFinalResult_Result() {}

type StreamError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *AnvilError            `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamError) Reset() {
	*x = StreamError{}
	mi := &file_anvil_v1_sidecar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamError) ProtoMessage() {}

func (x *StreamError) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_v1_sidecar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamError.ProtoReflect.Descriptor instead.
func (*StreamError) Descriptor() ([]byte, []int) {
	return file_anvil_v1_sidecar_proto_rawDescGZIP(), []int{7}
}

func (x *StreamError) GetError() *AnvilError {
	if x != nil {
		return x.Error
	}
	return nil
}

type Heartbeat struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TimestampMillis int64                  `protobuf:"varint,1,opt,name=timestamp_millis,json=timestampMillis,proto3" json:"timestamp_millis,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_anvil_v1_sidecar_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_v1_sidecar_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_anvil_v1_sidecar_proto_rawDescGZIP(), []int{8}
}

func (x *Heartbeat) GetTimestampMillis() int64 {
	if x != nil {
		return x.TimestampMillis
	}
	return 0
}

type CancelRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_anvil_v1_sidecar_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_v1_sidecar_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_anvil_v1_sidecar_proto_rawDescGZIP(), []int{9}
}

func (x *CancelRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cancelled     bool                   `protobuf:"varint,1,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_anvil_v1_sidecar_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_v1_sidecar_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_anvil_v1_sidecar_proto_rawDescGZIP(), []int{10}
}

func (x *CancelResponse) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_anvil_v1_sidecar_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_v1_sidecar_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_anvil_v1_sidecar_proto_rawDescGZIP(), []int{11}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_anvil_v1_sidecar_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_v1_sidecar_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_anvil_v1_sidecar_proto_rawDescGZIP(), []int{12}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ReloadConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SHA-256 of new_provider_config; sidecar verifies the hash before applying.
	NewConfigEpoch string `protobuf:"bytes,1,opt,name=new_config_epoch,json=newConfigEpoch,proto3" json:"new_config_epoch,omitempty"`
	// Serialized provider-config content (TOML bytes matching anvil.toml section).
	NewProviderConfig []byte `protobuf:"bytes,2,opt,name=new_provider_config,json=newProviderConfig,proto3" json:"new_provider_config,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReloadConfigRequest) Reset() {
	*x = ReloadConfigRequest{}
	mi := &file_anvil_v1_sidecar_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadConfigRequest) ProtoMessage() {}

func (x *ReloadConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_v1_sidecar_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadConfigRequest.ProtoReflect.Descriptor instead.
func (*ReloadConfigRequest) Descriptor() ([]byte, []int) {
	return file_anvil_v1_sidecar_proto_rawDescGZIP(), []int{13}
}

func (x *ReloadConfigRequest) GetNewConfigEpoch() string {
	if x != nil {
		return x.NewConfigEpoch
	}
	return ""
}

func (x *ReloadConfigRequest) GetNewProviderConfig() []byte {
	if x != nil {
		return x.NewProviderConfig
	}
	return nil
}

type ReloadConfigResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Set on failure; absent on success.
	Error *AnvilError `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Config epoch now active (new epoch on success, old epoch on failure).
	ActiveConfigEpoch string `protobuf:"bytes,3,opt,name=active_config_epoch,json=activeConfigEpoch,proto3" json:"active_config_epoch,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReloadConfigResponse) Reset() {
	*x = ReloadConfigResponse{}
	mi := &file_anvil_v1_sidecar_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadConfigResponse) ProtoMessage() {}

func (x *ReloadConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_v1_sidecar_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadConfigResponse.ProtoReflect.Descriptor instead.
func (*ReloadConfigResponse) Descriptor() ([]byte, []int) {
	return file_anvil_v1_sidecar_proto_rawDescGZIP(), []int{14}
}

func (x *ReloadConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReloadConfigResponse) GetError() *AnvilError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ReloadConfigResponse) GetActiveConfigEpoch() string {
	if x != nil {
		return x.ActiveConfigEpoch
	}
	return ""
}

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemPrompt  string                 `protobuf:"bytes,1,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	MaxTokens     *int32                 `protobuf:"varint,3,opt,name=max_tokens,json=maxTokens,proto3,oneof" json:"max_tokens,omitempty"`
	Temperature   *float32               `protobuf:"fixed32,4,opt,name=temperature,proto3,oneof" json:"temperature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_anvil_v1_sidecar_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_v1_sidecar_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_anvil_v1_sidecar_proto_rawDescGZIP(), []int{15}
}

func (x *ChatRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *ChatRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatRequest) GetMaxTokens() int32 {
	if x != nil && x.MaxTokens != nil {
		return *x.MaxTokens
	}
	return 0
}

func (x *ChatRequest) GetTemperature() float32 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_anvil_v1_sidecar_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_v1_sidecar_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_anvil_v1_sidecar_proto_rawDescGZIP(), []int{16}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Usage         *Usage                 `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	FinishReason  string                 `protobuf:"bytes,4,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_anvil_v1_sidecar_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_v1_sidecar_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_anvil_v1_sidecar_proto_rawDescGZIP(), []int{17}
}

func (x *ChatResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *ChatResponse) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

type EmbedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	mi := &file_anvil_v1_sidecar_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_v1_sidecar_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_anvil_v1_sidecar_proto_rawDescGZIP(), []int{18}
}

func (x *EmbedRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type EmbedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []float32              `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedResponse) Reset() {
	*x = EmbedResponse{}
	mi := &file_anvil_v1_sidecar_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResponse) ProtoMessage() {}

func (x *EmbedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_v1_sidecar_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResponse.ProtoReflect.Descriptor instead.
func (*EmbedResponse) Descriptor() ([]byte, []int) {
	return file_anvil_v1_sidecar_proto_rawDescGZIP(), []int{19}
}

func (x *EmbedResponse) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *EmbedResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type Usage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputTokens   int32                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int32                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_anvil_v1_sidecar_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_v1_sidecar_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_anvil_v1_sidecar_proto_rawDescGZIP(), []int{20}
}

func (x *Usage) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *Usage) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

type Credentials struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Credential:
	//
	//	*Credentials_ApiKey
	//	*Credentials_BearerToken
	Credential    isCredentials_Credential `protobuf_oneof:"credential"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_anvil_v1_sidecar_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_v1_sidecar_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_anvil_v1_sidecar_proto_rawDescGZIP(), []int{21}
}

func (x *Credentials) GetCredential() isCredentials_Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *Credentials) GetApiKey() string {
	if x != nil {
		if x, ok := x.Credential.(*Credentials_ApiKey); ok {
			return x.ApiKey
		}
	}
	return ""
}

func (x *Credentials) GetBearerToken() string {
	if x != nil {
		if x, ok := x.Credential.(*Credentials_BearerToken); ok {
			return x.BearerToken
		}
	}
	return ""
}

type isCredentials_Credential interface {
	isCredentials_Credential()
}

type Credentials_ApiKey struct {
	ApiKey string `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3,oneof"`
}

type Credentials_BearerToken struct {
	BearerToken string `protobuf:"bytes,2,opt,name=bearer_token,json=bearerToken,proto3,oneof"`
}

func (*Credentials_ApiKey) isCredentials_Credential() {}

func (*Credentials_BearerToken) isCredentials_Credential() {}

type Timeout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Millis        uint64                 `protobuf:"varint,1,opt,name=millis,proto3" json:"millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timeout) Reset() {
	*x = Timeout{}
	mi := &file_anvil_v1_sidecar_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timeout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timeout) ProtoMessage() {}

func (x *Timeout) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_v1_sidecar_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timeout.ProtoReflect.Descriptor instead.
func (*Timeout) Descriptor() ([]byte, []int) {
	return file_anvil_v1_sidecar_proto_rawDescGZIP(), []int{22}
}

func (x *Timeout) GetMillis() uint64 {
	if x != nil {
		return x.Millis
	}
	return 0
}

// AnvilError is the canonical error envelope.
// ErrorClass is pinned by hinge test test_error_class_count (pins=6).
type AnvilError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         ErrorClass             `protobuf:"varint,1,opt,name=class,proto3,enum=anvil.v1.ErrorClass" json:"class,omitempty"`
	VendorCode    string                 `protobuf:"bytes,2,opt,name=vendor_code,json=vendorCode,proto3" json:"vendor_code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnvilError) Reset() {
	*x = AnvilError{}
	mi := &file_anvil_v1_sidecar_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnvilError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnvilError) ProtoMessage() {}

func (x *AnvilError) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_v1_sidecar_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnvilError.ProtoReflect.Descriptor instead.
func (*AnvilError) Descriptor() ([]byte, []int) {
	return file_anvil_v1_sidecar_proto_rawDescGZIP(), []int{23}
}

func (x *AnvilError) GetClass() ErrorClass {
	if x != nil {
		return x.Class
	}
	return ErrorClass_ERROR_CLASS_UNSPECIFIED
}

func (x *AnvilError) GetVendorCode() string {
	if x != nil {
		return x.VendorCode
	}
	return ""
}

func (x *AnvilError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AnvilError) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_anvil_v1_sidecar_proto protoreflect.FileDescriptor

const file_anvil_v1_sidecar_proto_rawDesc = "" +
	"\n" +
	"\x16anvil/v1/sidecar.proto\x12\banvil.v1\"\xa3\x01\n" +
	"\x10HandshakeRequest\x122\n" +
	"\x15core_protocol_version\x18\x01 \x01(\tR\x13coreProtocolVersion\x12-\n" +
	"\x12supported_versions\x18\x02 \x03(\tR\x11supportedVersions\x12,\n" +
	"\x12vault_config_epoch\x18\x03 \x01(\tR\x10vaultConfigEpoch\"\xcb\x01\n" +
	"\x11HandshakeResponse\x12-\n" +
	"\x12negotiated_version\x18\x01 \x01(\tR\x11negotiatedVersion\x12'\n" +
	"\x0fsidecar_version\x18\x02 \x01(\tR\x0esidecarVersion\x12,\n" +
	"\x12sidecar_build_info\x18\x03 \x01(\tR\x10sidecarBuildInfo\x120\n" +
	"\x14sidecar_config_epoch\x18\x04 \x01(\tR\x12sidecarConfigEpoch\"\xe8\x02\n" +
	"\rInvokeRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x124\n" +
	"\x16provider_connection_id\x18\x03 \x01(\tR\x14providerConnectionId\x127\n" +
	"\vcredentials\x18\x04 \x01(\v2\x15.anvil.v1.CredentialsR\vcredentials\x12+\n" +
	"\x04chat\x18\x05 \x01(\v2\x15.anvil.v1.ChatRequestH\x00R\x04chat\x12.\n" +
	"\x05embed\x18\x06 \x01(\v2\x16.anvil.v1.EmbedRequestH\x00R\x05embed\x120\n" +
	"\atimeout\x18\a \x01(\v2\x11.anvil.v1.TimeoutH\x01R\atimeout\x88\x01\x01B\t\n" +
	"\apayloadB\n" +
	"\n" +
	"\b_timeout\"\xd0\x01\n" +
	"\x0eInvokeResponse\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12,\n" +
	"\x04chat\x18\x02 \x01(\v2\x16.anvil.v1.ChatResponseH\x00R\x04chat\x12/\n" +
	"\x05embed\x18\x03 \x01(\v2\x17.anvil.v1.EmbedResponseH\x00R\x05embed\x12,\n" +
	"\x05error\x18\x04 \x01(\v2\x14.anvil.v1.AnvilErrorH\x00R\x05errorB\b\n" +
	"\x06result\"\x8e\x02\n" +
	"\x11InvokeStreamEvent\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12'\n" +
	"\x05token\x18\x02 \x01(\v2\x0f.anvil.v1.TokenH\x00R\x05token\x12:\n" +
	"\ffinal_result\x18\x03 \x01(\v2\x15.anvil.v1.FinalResultH\x00R\vfinalResult\x12-\n" +
	"\x05error\x18\x04 \x01(\v2\x15.anvil.v1.StreamErrorH\x00R\x05error\x123\n" +
	"\theartbeat\x18\x05 \x01(\v2\x13.anvil.v1.HeartbeatH\x00R\theartbeatB\a\n" +
	"\x05event\"\x1b\n" +
	"\x05Token\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"v\n" +
	"\vFinalResult\x12,\n" +
	"\x04chat\x18\x01 \x01(\v2\x16.anvil.v1.ChatResponseH\x00R\x04chat\x12/\n" +
	"\x05embed\x18\x02 \x01(\v2\x17.anvil.v1.EmbedResponseH\x00R\x05embedB\b\n" +
	"\x06result\"9\n" +
	"\vStreamError\x12*\n" +
	"\x05error\x18\x01 \x01(\v2\x14.anvil.v1.AnvilErrorR\x05error\"6\n" +
	"\tHeartbeat\x12)\n" +
	"\x10timestamp_millis\x18\x01 \x01(\x03R\x0ftimestampMillis\"8\n" +
	"\rCancelRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\".\n" +
	"\x0eCancelResponse\x12\x1c\n" +
	"\tcancelled\x18\x01 \x01(\bR\tcancelled\"\x0f\n" +
	"\rHealthRequest\"D\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"o\n" +
	"\x13ReloadConfigRequest\x12(\n" +
	"\x10new_config_epoch\x18\x01 \x01(\tR\x0enewConfigEpoch\x12.\n" +
	"\x13new_provider_config\x18\x02 \x01(\fR\x11newProviderConfig\"\x8c\x01\n" +
	"\x14ReloadConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12*\n" +
	"\x05error\x18\x02 \x01(\v2\x14.anvil.v1.AnvilErrorR\x05error\x12.\n" +
	"\x13active_config_epoch\x18\x03 \x01(\tR\x11activeConfigEpoch\"\xcb\x01\n" +
	"\vChatRequest\x12#\n" +
	"\rsystem_prompt\x18\x01 \x01(\tR\fsystemPrompt\x12-\n" +
	"\bmessages\x18\x02 \x03(\v2\x11.anvil.v1.MessageR\bmessages\x12\"\n" +
	"\n" +
	"max_tokens\x18\x03 \x01(\x05H\x00R\tmaxTokens\x88\x01\x01\x12%\n" +
	"\vtemperature\x18\x04 \x01(\x02H\x01R\vtemperature\x88\x01\x01B\r\n" +
	"\v_max_tokensB\x0e\n" +
	"\f_temperature\"7\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x8a\x01\n" +
	"\fChatResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12%\n" +
	"\x05usage\x18\x03 \x01(\v2\x0f.anvil.v1.UsageR\x05usage\x12#\n" +
	"\rfinish_reason\x18\x04 \x01(\tR\ffinishReason\"\"\n" +
	"\fEmbedRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"C\n" +
	"\rEmbedResponse\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\"O\n" +
	"\x05Usage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x05R\foutputTokens\"[\n" +
	"\vCredentials\x12\x19\n" +
	"\aapi_key\x18\x01 \x01(\tH\x00R\x06apiKey\x12#\n" +
	"\fbearer_token\x18\x02 \x01(\tH\x00R\vbearerTokenB\f\n" +
	"\n" +
	"credential\"!\n" +
	"\aTimeout\x12\x16\n" +
	"\x06millis\x18\x01 \x01(\x04R\x06millis\"\xec\x01\n" +
	"\n" +
	"AnvilError\x12*\n" +
	"\x05class\x18\x01 \x01(\x0e2\x14.anvil.v1.ErrorClassR\x05class\x12\x1f\n" +
	"\vvendor_code\x18\x02 \x01(\tR\n" +
	"vendorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12;\n" +
	"\adetails\x18\x04 \x03(\v2!.anvil.v1.AnvilError.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xd9\x01\n" +
	"\n" +
	"ErrorClass\x12\x1b\n" +
	"\x17ERROR_CLASS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ERROR_CLASS_TRANSPORT\x10\x01\x12 \n" +
	"\x1cERROR_CLASS_PROVIDER_REFUSAL\x10\x02\x12 \n" +
	"\x1cERROR_CLASS_SCHEMA_VIOLATION\x10\x03\x12\x1b\n" +
	"\x17ERROR_CLASS_ADAPTER_BUG\x10\x04\x12\x17\n" +
	"\x13ERROR_CLASS_TIMEOUT\x10\x05\x12\x19\n" +
	"\x15ERROR_CLASS_CANCELLED\x10\x062\xa0\x03\n" +
	"\aSidecar\x12D\n" +
	"\tHandshake\x12\x1a.anvil.v1.HandshakeRequest\x1a\x1b.anvil.v1.HandshakeResponse\x12;\n" +
	"\x06Invoke\x12\x17.anvil.v1.InvokeRequest\x1a\x18.anvil.v1.InvokeResponse\x12I\n" +
	"\x0fInvokeStreaming\x12\x17.anvil.v1.InvokeRequest\x1a\x1b.anvil.v1.InvokeStreamEvent0\x01\x12;\n" +
	"\x06Cancel\x12\x17.anvil.v1.CancelRequest\x1a\x18.anvil.v1.CancelResponse\x12;\n" +
	"\x06Health\x12\x17.anvil.v1.HealthRequest\x1a\x18.anvil.v1.HealthResponse\x12M\n" +
	"\fReloadConfig\x12\x1d.anvil.v1.ReloadConfigRequest\x1a\x1e.anvil.v1.ReloadConfigResponseBCZAgithub.com/ai-nhancement/Anvil/sidecar/internal/contract;contractb\x06proto3"

var (
	file_anvil_v1_sidecar_proto_rawDescOnce sync.Once
	file_anvil_v1_sidecar_proto_rawDescData []byte
)

func file_anvil_v1_sidecar_proto_rawDescGZIP() []byte {
	file_anvil_v1_sidecar_proto_rawDescOnce.Do(func() {
		file_anvil_v1_sidecar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anvil_v1_sidecar_proto_rawDesc), len(file_anvil_v1_sidecar_proto_rawDesc)))
	})
	return file_anvil_v1_sidecar_proto_rawDescData
}

var file_anvil_v1_sidecar_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_anvil_v1_sidecar_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_anvil_v1_sidecar_proto_goTypes = []any{
	(ErrorClass)(0),              // 0: anvil.v1.ErrorClass
	(*HandshakeRequest)(nil),     // 1: anvil.v1.HandshakeRequest
	(*HandshakeResponse)(nil),    // 2: anvil.v1.HandshakeResponse
	(*InvokeRequest)(nil),        // 3: anvil.v1.InvokeRequest
	(*InvokeResponse)(nil),       // 4: anvil.v1.InvokeResponse
	(*InvokeStreamEvent)(nil),    // 5: anvil.v1.InvokeStreamEvent
	(*Token)(nil),                // 6: anvil.v1.Token
	(*FinalResult)(nil),          // 7: anvil.v1.FinalResult
	(*StreamError)(nil),          // 8: anvil.v1.StreamError
	(*Heartbeat)(nil),            // 9: anvil.v1.Heartbeat
	(*CancelRequest)(nil),        // 10: anvil.v1.CancelRequest
	(*CancelResponse)(nil),       // 11: anvil.v1.CancelResponse
	(*HealthRequest)(nil),        // 12: anvil.v1.HealthRequest
	(*HealthResponse)(nil),       // 13: anvil.v1.HealthResponse
	(*ReloadConfigRequest)(nil),  // 14: anvil.v1.ReloadConfigRequest
	(*ReloadConfigResponse)(nil), // 15: anvil.v1.ReloadConfigResponse
	(*ChatRequest)(nil),          // 16: anvil.v1.ChatRequest
	(*Message)(nil),              // 17: anvil.v1.Message
	(*ChatResponse)(nil),         // 18: anvil.v1.ChatResponse
	(*EmbedRequest)(nil),         // 19: anvil.v1.EmbedRequest
	(*EmbedResponse)(nil),        // 20: anvil.v1.EmbedResponse
	(*Usage)(nil),                // 21: anvil.v1.Usage
	(*Credentials)(nil),          // 22: anvil.v1.Credentials
	(*Timeout)(nil),              // 23: anvil.v1.Timeout
	(*AnvilError)(nil),           // 24: anvil.v1.AnvilError
	nil,                          // 25: anvil.v1.AnvilError.DetailsEntry
}
var file_anvil_v1_sidecar_proto_depIdxs = []int32{
	22, // 0: anvil.v1.InvokeRequest.credentials:type_name -> anvil.v1.Credentials
	16, // 1: anvil.v1.InvokeRequest.chat:type_name -> anvil.v1.ChatRequest
	19, // 2: anvil.v1.InvokeRequest.embed:type_name -> anvil.v1.EmbedRequest
	23, // 3: anvil.v1.InvokeRequest.timeout:type_name -> anvil.v1.Timeout
	18, // 4: anvil.v1.InvokeResponse.chat:type_name -> anvil.v1.ChatResponse
	20, // 5: anvil.v1.InvokeResponse.embed:type_name -> anvil.v1.EmbedResponse
	24, // 6: anvil.v1.InvokeResponse.error:type_name -> anvil.v1.AnvilError
	6,  // 7: anvil.v1.InvokeStreamEvent.token:type_name -> anvil.v1.Token
	7,  // 8: anvil.v1.InvokeStreamEvent.final_result:type_name -> anvil.v1.FinalResult
	8,  // 9: anvil.v1.InvokeStreamEvent.error:type_name -> anvil.v1.StreamError
	9,  // 10: anvil.v1.InvokeStreamEvent.heartbeat:type_name -> anvil.v1.Heartbeat
	18, // 11: anvil.v1.FinalResult.chat:type_name -> anvil.v1.ChatResponse
	20, // 12: anvil.v1.FinalResult.embed:type_name -> anvil.v1.EmbedResponse
	24, // 13: anvil.v1.StreamError.error:type_name -> anvil.v1.AnvilError
	24, // 14: anvil.v1.ReloadConfigResponse.error:type_name -> anvil.v1.AnvilError
	17, // 15: anvil.v1.ChatRequest.messages:type_name -> anvil.v1.Message
	21, // 16: anvil.v1.ChatResponse.usage:type_name -> anvil.v1.Usage
	0,  // 17: anvil.v1.AnvilError.class:type_name -> anvil.v1.ErrorClass
	25, // 18: anvil.v1.AnvilError.details:type_name -> anvil.v1.AnvilError.DetailsEntry
	1,  // 19: anvil.v1.Sidecar.Handshake:input_type -> anvil.v1.HandshakeRequest
	3,  // 20: anvil.v1.Sidecar.Invoke:input_type -> anvil.v1.InvokeRequest
	3,  // 21: anvil.v1.Sidecar.InvokeStreaming:input_type -> anvil.v1.InvokeRequest
	10, // 22: anvil.v1.Sidecar.Cancel:input_type -> anvil.v1.CancelRequest
	12, // 23: anvil.v1.Sidecar.Health:input_type -> anvil.v1.HealthRequest
	14, // 24: anvil.v1.Sidecar.ReloadConfig:input_type -> anvil.v1.ReloadConfigRequest
	2,  // 25: anvil.v1.Sidecar.Handshake:output_type -> anvil.v1.HandshakeResponse
	4,  // 26: anvil.v1.Sidecar.Invoke:output_type -> anvil.v1.InvokeResponse
	5,  // 27: anvil.v1.Sidecar.InvokeStreaming:output_type -> anvil.v1.InvokeStreamEvent
	11, // 28: anvil.v1.Sidecar.Cancel:output_type -> anvil.v1.CancelResponse
	13, // 29: anvil.v1.Sidecar.Health:output_type -> anvil.v1.HealthResponse
	15, // 30: anvil.v1.Sidecar.ReloadConfig:output_type -> anvil.v1.ReloadConfigResponse
	25, // [25:31] is the sub-list for method output_type
	19, // [19:25] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_anvil_v1_sidecar_proto_init() }
func file_anvil_v1_sidecar_proto_init() {
	if File_anvil_v1_sidecar_proto != nil {
		return
	}
	file_anvil_v1_sidecar_proto_msgTypes[2].OneofWrappers = []any{
		(*InvokeRequest_Chat)(nil),
		(*InvokeRequest_Embed)(nil),
	}
	file_anvil_v1_sidecar_proto_msgTypes[3].OneofWrappers = []any{
		(*InvokeResponse_Chat)(nil),
		(*InvokeResponse_Embed)(nil),
		(*InvokeResponse_Error)(nil),
	}
	file_anvil_v1_sidecar_proto_msgTypes[4].OneofWrappers = []any{
		(*InvokeStreamEvent_Token)(nil),
		(*InvokeStreamEvent_FinalResult)(nil),
		(*InvokeStreamEvent_Error)(nil),
		(*InvokeStreamEvent_Heartbeat)(nil),
	}
	file_anvil_v1_sidecar_proto_msgTypes[6].OneofWrappers = []any{
		(*FinalResult_Chat)(nil),
		(*FinalResult_Embed)(nil),
	}
	file_anvil_v1_sidecar_proto_msgTypes[15].OneofWrappers = []any{}
	file_anvil_v1_sidecar_proto_msgTypes[21].OneofWrappers = []any{
		(*Credentials_ApiKey)(nil),
		(*Credentials_BearerToken)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anvil_v1_sidecar_proto_rawDesc), len(file_anvil_v1_sidecar_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_anvil_v1_sidecar_proto_goTypes,
		DependencyIndexes: file_anvil_v1_sidecar_proto_depIdxs,
		EnumInfos:         file_anvil_v1_sidecar_proto_enumTypes,
		MessageInfos:      file_anvil_v1_sidecar_proto_msgTypes,
	}.Build()
	File_anvil_v1_sidecar_proto = out.File
	file_anvil_v1_sidecar_proto_goTypes = nil
	file_anvil_v1_sidecar_proto_depIdxs = nil
}
